services:
  frontend:
    container_name: bhayanak_streamer
    depends_on:
      - websocket_server
    image: "ghcr.io/thehimanshushekhar/bhayanak_streamer/frontend:latest"
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - 3000:3000

  websocket_server:
    container_name: websocket_server
    image: "ghcr.io/thehimanshushekhar/bhayanak_streamer/backend:latest"
    restart: unless-stopped
    ports:
      - 5000:5000

  # peer_server:
  #   container_name: peer_server
  #   image: peerjs/peerjs-server
  #   restart: unless-stopped
  #   environment:
  #     PEERSERVER_PATH: "/"
  #     PROXIED: true
  #   ports:
  #     - 9000:9000
