version: "3.9"
services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - 3000:3000
  
  websockets_server:
    build: ./backend
    restart: unless-stopped
    ports:
    - 3001:3001

networks:
  bhayanak_network:
    external: true